# Generated by Django 2.1.2 on 2018-10-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBuddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_user', to='TravelBuddy.User')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start', models.DateField(max_length=255)),
                ('end', models.DateField(max_length=255)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_plans', to='TravelBuddy.User')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_destination', to='TravelBuddy.Plan'),
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_start', to='TravelBuddy.Plan'),
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_end', to='TravelBuddy.Plan'),
        ),
    ]
