# Generated by Django 2.1.2 on 2018-10-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBuddy', '0002_auto_20181022_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='users',
            new_name='added_by',
        ),
    ]
