# Generated by Django 2.1.2 on 2018-10-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBuddy', '0003_auto_20181022_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='travel_from',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='travel_to',
        ),
    ]
